/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MIB_projekt;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;

import javax.swing.JButton;
import javax.swing.JFrame;




/**
 *
 * @author antti
 */
public class RegisterAlien extends javax.swing.JFrame {

    private static InfDB idb;
    private int alienID;
    // Create a connection to the database

    /**
     * Creates new form LoginForm
     * @param iidb
     */
    public RegisterAlien(InfDB iidb) {
        initComponents();
        idb = iidb;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alienIDText = new javax.swing.JTextField();
        areaText = new javax.swing.JTextField();
        registryDateText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        telefonText = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        agentText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Register a new alien, enter info below:");

        jLabel2.setText("Alien ID:");

        jLabel3.setText("Registry date:");

        jLabel4.setText("Email:");

        jLabel5.setText("Password:");

        jLabel6.setText("Name:");

        jLabel7.setText("Area ID:");

        alienIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienIDTextActionPerformed(evt);
            }
        });

        areaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaTextActionPerformed(evt);
            }
        });

        registryDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registryDateTextActionPerformed(evt);
            }
        });

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(telefonText);

        jLabel8.setText("Phone:");

        jLabel9.setText("Responsible agent:");

        jLabel10.setText("Choose race:");

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Worm", "Squid", "Boglodite" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel10)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(registryDateText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(passwordText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(areaText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(agentText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alienIDText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(comboType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(189, 189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alienIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registryDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alienIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienIDTextActionPerformed
                                          
    


    }//GEN-LAST:event_alienIDTextActionPerformed

    private void areaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaTextActionPerformed

    private void registryDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registryDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registryDateTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
   final var alienID = alienIDText.getText();
    String area = areaText.getText();
    String registryDate = registryDateText.getText();
    String email = emailText.getText();
    String password = passwordText.getText();
    String name = nameText.getText();
    String telefon = telefonText.getText();
    String agentID = agentText.getText();
    String selectedType = comboType.getSelectedItem().toString();

  
   // validitet för lösenord. maximum 6 bokstäver 
    if (password.length() > 6) {
        JOptionPane.showMessageDialog(areaText, "please 6 charachters maximum (password)");
    }
    // validitet för registreringsdatum för alien. måste vara ett datum i rätt format
    if (registryDate.length() != 10) {
        JOptionPane.showMessageDialog(areaText, "please enter email as exampled format: 2023-05-24(10 characters");
    }
    // validitet för telefonnummer. maximum 30 siffror
    if (telefon.length()> 30) {
        JOptionPane.showMessageDialog(areaText,  "Phone number has to be less than 30 digits");
    }
     if (name.length() > 20) {
            JOptionPane.showMessageDialog(areaText, "Name is too long. Maximum is 20 characters!");
    }
     if (email.length() > 20) {
         JOptionPane.showMessageDialog(areaText, "Email is too long. Maximum is 20 characters!");
     }
      
    // Anta att agentID är värdet du vill söka efter

try {
    // Skapa en SQL-fråga för att söka efter Agent_ID i tabellen
    String sql = "SELECT Agent_ID FROM agent WHERE Agent_ID = '" + agentID + "'";

    // Utför SQL-frågan och hämta resultatet
    String existingAgentID = idb.fetchSingle(sql);

    // Kontrollera om resultatet är null, vilket indikerar att inget matchande Agent_ID hittades
    if (existingAgentID == null) {
        JOptionPane.showMessageDialog(areaText, "Inget agent registrerad med ID: " + agentID);
    
    }
} catch (InfException e) {
   JOptionPane.showMessageDialog(areaText,"Ett fel uppstod vid sökningen i databasen: " + e.getMessage());
} try {
    // Skapa en SQL-fråga för att söka efter Plats_ID i tabellen
    String sql = "SELECT Plats_ID FROM plats WHERE Plats_ID = '" + area + "'";

    // Utför SQL-frågan och hämta resultatet
    String existingPlatsID = idb.fetchSingle(sql);

    // Kontrollera om resultatet är null, vilket indikerar att inget matchande Plats_ID hittades
    if (existingPlatsID == null) {
        JOptionPane.showMessageDialog(null, "Ingen plats registrerad med ID: " + area);
    } else {
        // Platsen hittades, fortsätt med övrig logik här
        // ...
    }
} catch (InfException e) {
    JOptionPane.showMessageDialog(null, "Ett fel uppstod vid sökningen i databasen: " + e.getMessage());
}
try {
    // Skapa en SQL-fråga för att söka efter Alien_ID i tabellen
    String sql = "SELECT Alien_ID FROM alien WHERE Alien_ID = '" + alienID + "'";

    // Utför SQL-frågan och hämta resultatet
    String existingAlienID = idb.fetchSingle(sql);

    // Kontrollera om resultatet är null, vilket indikerar att inget matchande Alien_ID hittades
    if (existingAlienID == null) {
        // Inget Alien_ID finns registrerat, fortsätt med önskad logik här
        // ...
    } else {
        JOptionPane.showMessageDialog(null, "Alien med ID: " + alienID + " finns redan registrerad");
    }
} catch (InfException e) {
    JOptionPane.showMessageDialog(null, "Ett fel uppstod vid sökningen i databasen: " + e.getMessage());
}




    // Kontrollera om area är tomt, i så fall använd null-värde
    if (area.isEmpty()) {
        area = null;
    }


try {
    // Check if the alien already exists
    String query = "SELECT COUNT(*) FROM alien WHERE Alien_ID = '" + alienID + "' AND Plats = '" + area + "'";
    String result = idb.fetchSingle(query);
    int count = Integer.parseInt(result);

    if (count > 0) {
        JOptionPane.showMessageDialog(this, "Alien with ID " + alienID + " already exists in the database.");
    } else {
        // Insert the new alien with the specified agent ID
        idb.insert("INSERT INTO alien (Alien_ID, Registreringsdatum, Epost, Losenord, Namn, Telefon, Plats, Ansvarig_Agent) VALUES ('" + alienID + "', '" + registryDate + "', '" + email + "', '" + password + "', '" + name + "', '" + telefon + "', '" + area + "', '" + agentID +"')");
        JOptionPane.showMessageDialog(this, "Alien with ID " + alienID + " added to the database.");
    }
    //om man trycker in worm i comboboxen kommer nästa fönster som berättar vad för ytterliggare information som ska registreras. i detta fall är det längden på alien
    if (selectedType.equalsIgnoreCase("Worm")) {

                JFrame frame = new JFrame("Extra information:");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                JButton button = new JButton("Add extra information");
                button.addActionListener(e -> {
                    String input = JOptionPane.showInputDialog(frame, "Enter length in digits only:");
                    if (input != null && !input.isEmpty()) {
                        try {
// här följer alienID från tidigare fönster med längden på alien in i tabellen i sql.
                            
                            int langd = Integer.parseInt(input);
                            idb.insert("INSERT INTO worm (Alien_ID, Langd) Values('" + alienID + "'," + langd + ")");
                            JOptionPane.showMessageDialog(frame, "Updated successfully!");
                        } catch (InfException ex) {
                            Logger.getLogger(RegisterAlien.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });

                frame.getContentPane().add(button);
                frame.pack();
                frame.setVisible(true);
// en else sats utifall man registrerar squid, exakt samma fast squid anger man antal armar istället för längd
            } else {
        if (selectedType.equalsIgnoreCase("Squid")) {
            JFrame frame = new JFrame("Extra information");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            JButton button = new JButton("Add extra information");
            button.addActionListener(e -> {
                String input = JOptionPane.showInputDialog("Enter antal armar:");
                if (input != null && !input.isEmpty()) {
                    try {
                        
                        
                        int antalArmar = Integer.parseInt(input);
                        idb.insert("INSERT INTO squid (Alien_ID, Antal_Armar) Values ('" + alienID + "'," + antalArmar + ")");
                        JOptionPane.showMessageDialog(frame, "Updated succesfully!");
                    } catch (InfException ex) {
                        Logger.getLogger(RegisterAlien.class.getName()).log(Level.SEVERE,null,ex);
                    }
                }
            });
            frame.getContentPane().add(button);
                frame.pack();
                frame.setVisible(true);
                // här anger man boglodites antal boogies. 3e alternativet av aliens ras man kan registrera.
        } else {
            if (selectedType.equalsIgnoreCase("Boglodite")) {
                JFrame frame = new JFrame("Extra information");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                JButton button = new JButton("Add extra information");
                button.addActionListener(e-> {
                    String input = JOptionPane.showInputDialog("Enter antal boogies:");
                    if (input != null && !input.isEmpty()) {
                        try {
                            
                            int antalBoogies = Integer.parseInt(input);
                            idb.insert("INSERT INTO boglodite (Alien_ID, Antal_Boogies) Values ('" + alienID + "'," + antalBoogies + ")");
                            JOptionPane.showMessageDialog(frame, "Updated succesfullt!");
                        } catch (InfException ex) {
                        Logger.getLogger(RegisterAlien.class.getName()).log(Level.SEVERE,null,ex);
                    }
                }
            });
            frame.getContentPane().add(button);
                frame.pack();
                frame.setVisible(true);
                        }
                    }
    }
            
        
    
    // kladd
    
} catch (InfException ex) {
    Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
}


    


    }//GEN-LAST:event_registerButtonActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agentText;
    private javax.swing.JTextField alienIDText;
    private javax.swing.JTextField areaText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField passwordText;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField registryDateText;
    private javax.swing.JTextPane telefonText;
    // End of variables declaration//GEN-END:variables
}
